version: "3.7"
services:
  ambianic-edge:
    container_name: ambianic-edge
    restart: unless-stopped
    privileged: true
    image: ambianic/ambianic-edge:latest
    network_mode: "host"
    privileged: true
    devices:
      - "/dev/video0:/dev/video0"
    env_file:
      - .env.default
      - .env
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /opt/vc:/opt/vc
      # Ambianic Edge will look for its config.yaml file in the directory specified below
      # It will also store logs and data files under the same directory
      - ./data:/workspace
      - /opt/ambianic/:/workspace/.peerjsrc
      - /etc/ambianic/:/workspace/config.yaml
      # - ${SECRETS}:/workspace/secrets.yaml
    restart: on-failure
    environment:
      - LD_LIBRARY_PATH=/opt/vc/lib
    healthcheck:
      test: ["CMD", "curl", "-sI", "http://127.0.0.1:8778/"]
      interval: 300s
      timeout: 3s
      retries: 10
    labels: 
      com.centurylinklabs.watchtower.enable: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
  # use watchtower to automatically and gracefully update ambianic-edge docker images
  watchtower:
    container_name: ambianic-watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # with --cleanup watchtower will remove old unused docker images
    command: --cleanup  --label-enable
