# This is a basic workflow to help you get started with Actions

name: CI - build custom Raspberry Pi OS image for Ambianic Edge devices

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install pi-gen required dependencies
        run: |
          apt-get install coreutils quilt parted qemu-user-static debootstrap zerofree zip \
dosfstools bsdtar libcap2-bin grep rsync xz-utils file git curl bc


      - name: Setup Pi-Gen Environment
        run: |
          echo Setup Pi-Gen Environment
          echo "IMG_NAME=Ambianic_Edge_rpi_image" > config

      # Checkout the latest pi-gen repo code
      - name: Checkout the latest pi-gen repo code
        run: git clone https://github.com/RPi-Distro/pi-gen.git

      # Run pi-gen script
      - name: Run pi-gen script
        run: |
          ls -al
          cd pi-gen
          ls -al
          ./build.sh

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Finishing pi-gen script...
          echo Ambianic Edge rpi image build finished successfully!
